### ISSUE TITLE
Create Hero component of Work Page

### ISSUE THREAD

**Issue by divyansh12git** [desco-nitp/club-website#13]
## Contribute: 

1.  Under other_component/Home_components folder create a folder named hero and under which start working
2.  Add this component to home page

![work_hero](https://github.com/desco-nitp/club-website/assets/123203281/e5cb24ed-7587-4fb7-842e-92fe10b7ee74)

**Comment by maithilee24** [comment]
Assign me

**Comment by divyansh12git** [comment]
@maithilee24 , one thing u can use  image for "Got a project part" from figma, I dont think it will have any significant role.
