### ISSUE TITLE
Create Hero component of Blog Page

### ISSUE THREAD

**Issue by divyansh12git** [desco-nitp/club-website#14]
## Contribute: 

1.  Under other_component/Blog_components folder create a folder named hero and under which start working
2.  Add this component to blogpage

![blog_hero](https://github.com/desco-nitp/club-website/assets/123203281/e4c0d35e-e521-4eb0-ab7e-7bcd33103acd)

**Comment by Abhinav1341** [comment]
#24 Please check it.
