### ISSUE TITLE
Create Work Page Component

### ISSUE THREAD

**Issue by divyansh12git** [desco-nitp/club-website#27]
## Implementation:

1.  All the components should be in components/works directory.
2.  Create 2 components: first Banner for the different teams: brand, digital art,3d,etc, second a image components which will mutate under Banner (through arr.map)
3. Create the main component (Works) which will have all the banners. Render it on works page.
4. Make sure u should pass a list and its props dynamically through the components.

![work_compo](https://github.com/desco-nitp/club-website/assets/123203281/935508d3-5a05-4cc3-bfa9-716ff4fd17c9)

**Comment by maithilee24** [comment]
Assign me
