### ISSUE TITLE
Create Latest Posts component in Blog page.

### ISSUE THREAD

**Issue by divyansh12git** [desco-nitp/club-website#29]
##Implementation

1. All the components should be in components/blogs/latest directory.
2.  Create 2 components LatestPost and Post the the Post should be rendered in latestPost dynamically (through arr.map). And the data to Post the image link and text should be send thu props.

Please do not hard code it, make as dynamic as possible.

![blog_latestpost](https://github.com/desco-nitp/club-website/assets/123203281/c42bd1b4-b80f-4e30-a761-32404ce8a309)

**Comment by 007ANSH** [comment]
assign this to me please.

**Comment by divyansh12git** [comment]
closing this issue as work completed by @007ANSH
