### ISSUE TITLE
Create Event Component for event page

### ISSUE THREAD

**Issue by divyansh12git** [desco-nitp/club-website#30]
## Implementation:

1. All the components should be in components/event directory.
2.  Make 3 Component  PastEvents, Upcoming  and the banner.
3. The Banner should be rendered in PastEvent and Upcoming Event Component dynamically (arr.map) and the data to banner like image link sholud be passed through props.
4. Please do not hard code it, make as dynamic as possible.

![event_compo](https://github.com/desco-nitp/club-website/assets/123203281/d1a11e78-f164-466a-9361-214fc10cae00)

**Comment by mitali-dxt** [comment]
Assign me this

**Comment by divyansh12git** [comment]
closing this isssue... as task completed successfully
